### ISSUE TITLE
[BUG] Can`t use "npm install open-im-sdk-node" get this package

### ISSUE THREAD

**Issue by freedom9527** [openimsdk/openim-sdk-electron#1]
### OpenIM Server Version

master

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/open-im-sdk-node - Not found
npm ERR! 404
npm ERR! 404  'open-im-sdk-node@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Bloomingg** [comment]
npm i @openim/node-client-sdk
