### ISSUE TITLE
[FEATURE REQUEST] Added information from local database

### ISSUE THREAD

**Issue by Ayloss** [openimsdk/openim-sdk-electron#7]
### Why this feature?

我看electron的sdk会在指定的数据目录下创建sqlite数据库，但SDK中似乎只提供了从网络请求中获取数据的方法。
期望增加直接从数据库中读取本地缓存的方法，以便在数据部分同步失败或断网场景下能有初始数据。
![image](https://github.com/user-attachments/assets/c1544525-a6c1-45f3-a8c0-440ae3bfa33d)

### Suggested Solution

例如SDK以下的接口：
getFriendList
getAllConversationList

增加从数据库获取的方法:
getFriendListFromDB
getAllConversationListFromDB

**Comment by Bloomingg** [comment]
In fact, it is now obtained from the local db.
