### ISSUE TITLE
[BUG] Getting Error"incompatible architecture(have 'arm64', need 'x86_64h' or 'x86_64')" when loading mac_x64 libopenimsdk.dylib 

### ISSUE THREAD

**Issue by Ayloss** [openimsdk/openim-sdk-electron#8]
### OpenIM Server Version

@openim/electron-client-sdk 1.0.8

### Operating System and CPU Architecture

macOS (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

I try to init electron sdk on a intel x64 cpu mac mini，but get error below. 
It seems that x64 and arm64 dylib are the same one, they have same file size.
![企业微信截图_17272453549080](https://github.com/user-attachments/assets/f31ba044-3182-478d-8bf5-6102b72b9a10)
![企业微信截图_17272451603208](https://github.com/user-attachments/assets/dde602f2-98ad-4bef-bf6f-9dfbf68e5974)

**Comment by Bloomingg** [comment]
The problem has been fixed in version 1.1.0.
